config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'yearbook#index'
  get 'tags/:tag', to: 'photo#index', as: "tag"

  resources :wdiers do
    resources :posts
  end
  resources :wdiers do
    resources :students
  end

  resources :wdiers do
    resources :instructors
  end

  resources :photos
end

app/models/wdier.rb
class Wdier < ActiveRecord::Base
  belongs_to :yearbook
  belongs_to :instructors
  belongs_to :students
  has_one :codey
  has_many :comments
  has_many :posts
  has_many :negatives
  has_many :photos, through: :negatives
end

app/controllers/wdiers_controller.rb
class WdiersController < ApplicationController


  def index
    @wdiers = Wdier.all
    @instructors = Wdier.where(role: "Instructor")
    @students = Wdier.where(role: "Student")
  end

  def new
    @wdier = Wdier.new
  end

  def create
    @wdier = Wdier.create!(wdier_params)

    redirect_to wdiers_path(@wdier)
  end

  def show
    @wdier = Wdier.find(params[:id])
    # @instructor = Wdier.find.where(role: "Instructor")
    # @student = Wdier.where(role: "Student")
    @squad = Wdier.where(squad_name: @wdier.squad_name)


  end


  def edit
    @wdier = Wdier.find(params[:id])
  end

  def update
    @wdier = Wdier.find(params[:id])
    @wdier.update(wdier_params)

    redirect_to wdier_path(@wdier)
  end

  def destroy
    @wdier = Wdier.find(params[:id])
    @wdier.destroy

    redirect_to wdiers_path(@wdier)
  end

  def photos
    @wdier = @wdier.photos.find(params[:id])
  end

  def attr_accessible
    @photo = Photo.find(params[:id])
  end

  def tag_cloud
    @tags = Post.tag_counts_on(:tags)
  end

  def squad
    @wdier = Wdier.find(params[:id])
    @squad = Wdier.where(squad_name: @wdier.squad_name)
  end

  private
  def wdier_params
    params.require(:wdier).permit(:name, :img_url, :quote, :teaching, :memory, :favlang, :wisewords, :tag_list, :github_url, :portfolio_url, :project1_url, :project2_url, :project3_url, :project4_url, :quote, :q1, :q2, :q3, :fb, :linkedin, :email, :role, :squad_name, :squad_img)
  end
end

app/views/wdiers/edit.html.erb
<h2> Edit Wdier </h2>
<%= form_for [@wdier] do |f| %>

  <%=f.label :name %>
  <%=f.text_field :name %>
  <%=f.label :img_url %>
  <%=f.text_field :img_url %>
  <%=f.label :github_url %>
  <%=f.text_field :github_url %>
  <%=f.label :portfolio_url %>
  <%=f.text_field :portfolio_url %>
  <%=f.label :project1_url %>
  <%=f.text_field :project1_url %>
  <%=f.label :project2_url %>
  <%=f.text_field :project2_url %>
  <%=f.label :project3_url %>
  <%=f.text_field :project3_url %>
  <%=f.label :quote %>
  <%=f.text_field :quote %>
  <%=f.label :squad_name %>
  <%=f.text_field :squad_name %>
  <%=f.label :teaching %>
  <%=f.text_field :teaching %>
  <%=f.label :memory %>
  <%=f.text_field :memory %>
  <%=f.label :favlang %>
  <%=f.text_field :favlang  %>
  <%=f.label :wisewords %>
  <%=f.text_field :wisewords %>
  <%=f.label :tag_list %>
  <%=f.text_field :tag_list %>
  <%=f.label :q1 %>
  <%=f.text_field :q1 %>
  <%=f.label :q2 %>
  <%=f.text_field :q2 %>
  <%=f.label :q3 %>
  <%=f.text_field :q3 %>
  <%=f.label :fb %>
  <%=f.text_field :fb %>
  <%=f.label :linkedin %>
  <%=f.text_field :linkedin %>
  <%=f.label :squad_id %>
  <%=f.text_field :squad_id %>
  <%=f.label :student_id %>
  <%=f.text_field :student_id %>
  <%=f.label :instructor_id %>
  <%=f.text_field :instructor_id %>
  <%=f.label :codey_id %>
  <%=f.text_field :codey_id %>
  <%=f.label :role %>
  <%=f.text_field :role %>

  <%=f.submit%>
  <% end %>
  <footer>
    <%= image_tag("blkdc.png") %>
  </footer>

app/views/wdiers/index.html.erb
<section id="wdierIndex">
  <section id="instructorArea">
  </section>
    <div class="inner">
      <div class="inner-shadow mustard page-header">
        <h4>Instructors</h4></div>
        <div class="thumbnail-grid flex index">
          <% @instructors.each do |wdier| %>
          <div class="flex-item"><%= link_to image_tag(wdier.img_url), wdier_path(wdier) %>
            <figure class="i1">
              <figcaption><%= link_to wdier.name, wdier_path(wdier) %></figcaption>
            </figure>
          </div>
          <% end %>
        </div>
      </div>
    <section id="studentArea">
    </section>
    <div class="inner">
      <div class="inner-shadow mustard page-header">
        <h4>Students</h4></div>
        <div class="thumbnail-grid flex index">
          <% @students.each do |wdier| %>
          <div class="flex-item"><%= link_to image_tag(wdier.img_url), wdier_path(wdier) %>
            <figure class="i1">
              <figcaption><%= link_to wdier.name, wdier_path(wdier) %></figcaption>
            </figure>
          </div>
          <% end %>
        </div>
      </div>
    </section>
  <footer>
    <%= image_tag("blkdc.png") %>
  </footer>

app/views/wdiers/show.html.erb
<%= link_to "edit", edit_wdier_path(@wdier)%>
</br>
<section id="wdierShow">
  <div class="wrapper">
    <div class="profileImg"><%= image_tag @wdier.img_url %>
    </div>
    <div class="box">
      <div class="cover-pic">
        <div class="profile-name">
          <h2 class="inner-shadow mustard"><%= @wdier.name %></h2>
        </div>
        <div class="page-header social">
          <%= link_to @wdier.portfolio_url, class:"icon-link round desktop fill" do %>
          <i class="fa fa-desktop"></i></a>
          <% end %>
          <%= link_to @wdier.github_url, class: "icon-link round github fill" do %>
          <i class="fa fa-github"></i></a>
          <% end %>
          <%= link_to @wdier.fb, class:"icon-link round facebook fill" do %>
          <i class="fa fa-facebook"></i></a>
          <% end %>
          <%= link_to @wdier.linkedin, class:"icon-link round linkedin fill" do %>
          <i class="fa fa-linkedin"></i></a>
          <% end %>
          <%= link_to @wdier.email, class:"icon-link round envelope fill" do %>
          <i class="fa fa-envelope"></i></a>
          <% end %>
        </div>
      </div>
      <div class="quote_container">
        <div class="quote">
          <%= image_tag("quote-front-blue copy.png") %>
          <%= @wdier.quote %>
          <%= image_tag("quote-end-blue.png") %>
        </div>
      </div>
      <div class="topContainer">
        <% if @wdier.teaching.present? %>
        <div class="teaching">
          <div class="inner-shadow mustard">
          <h2>I've been teaching for</h2></div><h3><%= @wdier.teaching %></h3>
        </div>
        <% end %>
          <%  if @wdier.memory.present? %>
          <div class="memory">
            <div class="inner-shadow mustard">
          <h2>My favorite WDI8 Memory</h2></div><h3><%= @wdier.memory %></h3>
        </div>
        <% end %>
        <% if @wdier.favlang.present? %>
        <div class="lang">
          <div class="inner-shadow mustard">
          <h2>My favorite programming language</h2></div><h3><%= @wdier.favlang %></h3>
        </div>
        <% end %>
        <% if @wdier.wisewords.present? %>
        <div class="wisdom">
          <div class="inner-shadow mustard">
          <h2>Words of wisdom for the students</h2></div><h3><%= @wdier.wisewords %></h3>
        </div>
        <% end %>
        <% if @wdier.q1.present? %>
        <div class="q1">
          <div class="inner-shadow mustard">
          <h2>My favorite WDI8 Memory</h2></div><h3><%= @wdier.q1 %></h3>
        </div>
        <% end %>
        <%  if @wdier.q2.present? %>
        <div class="q2">
          <div class="inner-shadow mustard">
          <h2> I can't live without my</h2></div><h3><%= @wdier.q2 %></h3>
        </div>
        <% end %>
        <%  if @wdier.q3.present? %>
        <div class="q3">
          <div class="inner-shadow mustard">
          <h2>My guilty pleasure is... </h2></div><h3></br><%= @wdier.q3 %></h3>
        </div>
        <% end %>
        </div>
        <% if @wdier.project2_url.present? %>
          <div class="projectGallery">
            <div class="inner-shadow mustard">
            <h4>Project Gallery</h4>
            <div class="thumbnail-grid figure">
              <%=link_to image_tag("project1.png"), @wdier.project1_url if @wdier.project1_url? %>
              <%=link_to image_tag("project2.png"), @wdier.project2_url if @wdier.project2_url? %>
              <%=link_to image_tag("project3.png"), @wdier.project3_url if @wdier.project3_url? %>
            </div>
            </div>
            </div>
            <% end %>
            <div class="squadGallery">
              <div class="inner-shadow mustard">
                <h4>SQUAD</h4>
                <h4> <%= @wdier.squad_name %></h4>
              </br></div>
              <div class="squad_img"><%= image_tag(@wdier.squad_img) %>
          </div>
              <div class="index thumbnail-grid figure">
                <% @squad.each do |squad| %>
                <%= link_to image_tag(squad.img_url), wdier_path(squad) %>
                <% end %>
              </div>
            </div>

          <div class="photo">
            <div class="photoGallery">
              <div class="inner-shadow mustard">
                <h4>Pix</h4>
              </div>
              <ul>
                <li class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                  <% @wdier.photos.each do |photo| %>
                  <%= image_tag photo.img_url %></li>
                  <% end %>
                </ul>
                <button><%= link_to "Add new photo", new_photo_path(@wdier) %></button>
              </div>
            </div>
            <div class="comment">
              <div class="commentGallery">
                <div class="overlay">
                  <div class="inner-shadow mustard">
                    <h4>keep in touch...</h4>
                  </div>
                  <% @wdier.posts.each do |post| %>
                  <div class="name">
                    <%= post.name %></br>
                    <%= post.body %>
                  </div>
                  <% end %>
                  <button><%= link_to "Add new comment", new_wdier_post_path(@wdier) %> </button>

                  <% if current_user && current_user == post.user %>
                  <%= link_to "Edit", edit_wdier_post_path(@wdier) %> |
                  <%= link_to "Delete", wdier_post_path(@wdier), method: :delete %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <footer>
        <%= image_tag("blkdc.png") %>
      </footer>