config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'yearbook#index'
  get 'tags/:tag', to: 'photo#index', as: "tag"

  resources :wdiers do
    resources :posts
  end
  resources :wdiers do
    resources :students
  end

  resources :wdiers do
    resources :instructors
  end

  resources :photos
end

app/models/yearbook.rb
class Yearbook < ActiveRecord::Base
  has_many :squads
  has_many :students
  has_many :instructors
  has_many :codeys
  has_many :photos
  has_many :users
  has_many :wdiers
end

app/controllers/yearbook_controller.rb
class YearbookController < ApplicationController

  def index
    @yearbook = Yearbook.all
  end

  def show
    @yearbook = Yearbook.find(params[:id])
  end

  def new
    @yearbook = Yearbook.new
  end

  def create
    @yearbook = Yearbook.create!(yearbook_params)

    redirect_to yearbook_path(@yearbook)
  end

  def edit
    @yearbook = Yearbook.find(params[:id])
  end

  def update
    @yearbook = Yearbook.find(params[:id])
    @yearbook.update(yearbook_params)
    redirect_to yearbook_path(@yearbook)
  end

  def destroy
    @yearbook = Yearbook.find(params[:id])
    @yearbook.destroy
    redirect_to yearbook_path(@yearbook)
  end

  def attr_accessible
    @photo = Photo.find(params[:id])
  end

  private
  def yearbook_params
    params.require(:yearbook).permit(:photos, :name, :tag_list)
  end
end

app/views/yearbook/index.html.erb
<section id="yearbookIndex">
  <section class="yearbookCover">
    <!-- <div class="overlay"> -->
    <div class="text-overlay">
      <div class="inner-shadow mustard">
      </br>
    </br>
  </br>
  <span>WDI</br>YEARBOOK</span>
</div>
</div>
</section>
<!-- <section class="space">
<div class="inner-shadow mustard">
</section> -->

<section class="words">
  <div class="inner-shadow mustard">
  </br>
  <h4>INSTRUCTOR'S WORDS OF WISDOM</h4>
</div>
<div class="container">
  <div class="box_center wisewords">
    <div class="center">
      <%= image_tag"http://i.imgur.com/NivMS84m.jpg"%>
    </div>
    <div class="boxHeader-center">
    <h3>Shanaz Chowdhery</h3>
  </div>
  <div class="quotemark-open">
    <%= image_tag "quote-front-black" %>
  </div>
  <div class="textContainer">
    <h2>Your success was no accident or fluke. It was a combination of your hard work, your grit, your determination, your late nights, your early mornings, your failures, and your  breakthroughs. If nothing, I hope that you’ve learned that there’s nothing that you can’t do. You’ve earned this and we’re so proud of you.</h2>
  </div>
  <div class="quotemark-close">
    <%= image_tag "quote-end-black" %>
  </div>
</div>
</div>
  <div class="container">
    <div class="box_left wisewords">
      <div class="left">
        <%= image_tag"https://pbs.twimg.com/profile_images/494612822740197377/4ldXwgN5_400x400.jpeg"%>
      </div>
      <div class="boxHeader-left">
      <h3>Jesse Shawl</h3>
    </div>
    <div class="quotemark-open">
      <%= image_tag "quote-front-black" %>
    </div>
    <div class="textContainer">
      <h2>The learning is endless. Learn to love mistakes.</h2>
    </div>
    <div class="quotemark-close">
      <%= image_tag "quote-end-black" %>
    </div>
  </div>
  </div>
  <div class="container">
    <div class="box_right wisewords">
      <div class="right">
        <%= image_tag "https://avatars3.githubusercontent.com/u/6268177?v=3&s=460" %>
      </div>
      <div class="boxHeader-right">
      <h3> Robin Thomas</h3>
    </div>
    <div class="quotemark-open">
      <%= image_tag "quote-front-black" %>
    </div>
    <div class="robintextContainer">
      <h2> Go teach! Do a free "Beginner's HTML" class at your library or church. What you have, everyone else wants! </h2>
    </div>
    <div class="robinquotemark-close">
      <%= image_tag "quote-end-black" %>
    </div>
  </div>
</div>
  <div class="container">
    <div class="box_left wisewords">
      <div class="left">
        <%= image_tag "https://pbs.twimg.com/profile_images/609055940596236288/RfQHyuDo.jpg" %>
      </div>
      <div class="boxHeader-left">
      <h3>Adrian Maseda</h3>
    </div>
    <div class="quotemark-open">
      <%= image_tag "quote-front-black" %>
    </div>
    <div class="textContainer">
      <h2>Deploy early and often.</h2>
    </div>
    <div class="quotemark-close">
      <%= image_tag "quote-end-black" %>
    </div>
  </div>
</div>
  <div class="container">
    <div class="box_right wisewords">
      <div class="right">
        <%= image_tag"https://avatars3.githubusercontent.com/u/10698044?v=3&s=460" %>
      </div>
      <div class="boxHeader-right">
      <h3>Nick Olds</h3>
    </div>
    <div class="quotemark-open">
      <%= image_tag "quote-front-black" %>
    </div>
    <div class="textContainer">
      <h2> Technologies fade, Concepts do not. </h2>
    </div>
    <div class="quotemark-close">
      <%= image_tag "quote-end-black" %>
    </div>
  </div>
</div>
    <div class="container">
      <div class="box_left wisewords">
        <div class="left">
          <%= image_tag"https://media.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAASvAAAAJDM3ZWUwOWI5LTE1YzQtNGY1Yi05NTZlLWQ2OTYwZTdlMDUyMQ.jpg"%>
        </div>
        <div class="boxHeader-left">
        <h3>Joe Zaretsky</h3>
        </div>
        <div class="quotemark-open">
          <%= image_tag "quote-front-black" %>
        </div>
        <div class="textContainer">
        <h2> You know WAY more than you think you do! </h2>
      </div>
      <div class="quotemark-close">
        <%= image_tag "quote-end-black" %>
      </div>
    </div>
    </div>
    <div class="container">
      <div class="box_right wisewords">
        <div class="right">
          <%= image_tag"http://media.vogue.com/r//2015/03/11/cinderella-gifs-steven-dam-06.gif"%>
        </div>
        <div class="boxHeader-right">
        <h3>Matt Scilipoti</h3>
      </div>
      <div class="quotemark-open">
        <%= image_tag "quote-front-black" %>
      </div>
      <div class="textContainer">
        <h2>Small steps.  Make a change.  See it work.  When it doesn't, remember you are not alone.</h2>
      </div>
      <div class="quotemark-close">
        <%= image_tag "quote-end-black" %>
      </div>
    </div>
  </div>
      <div class="container">
        <div class="box_bm wisewords">
          <div class="bm">
            <%= image_tag"http://i.imgur.com/3us7T1el.jpg"%>
          </div>
          <div class="boxHeader-bm">
          <h3>Brian Martinowich</h3>
        </div>
        <div class="quotemark-open">
          <%= image_tag "quote-front-black" %>
        </div>
        <div class="textContainer">
          <h2>You are all destined to do great things!  Reflect back on everything that you have learned and accomplished in the last 12 weeks. The future is bright and there is nothing that can stand in your way. As Ali said - 'Impossible is not a fact. It's an opinion. Impossible is not a declaration. It's a dare. Impossible is potential. Impossible is temporary. Impossible is nothing.'</h2>
        </div>
        <div class="quotemark-close">
          <%= image_tag "quote-end-black" %>
        </div>
      </div>
      </div>
  </section>
  <div class="space">
    </div>
    <section class="middle">
      <div class="middle_container">
        <div class="wdiers">
          <div class="text-overlay">
            <div class="inner-shadow mustard">
            </br>
          </br>
          <span2>WDI8 </span2>
        </div>
        <!-- </div> -->
        <div class="links">
          <%=link_to image_tag("instructor.png"), wdiers_path(anchor: "instructorArea")%>
          <%=link_to image_tag("student.png"), wdiers_path(anchor: "studentArea")%>
        </div>
      </div>
    </div>
  </section>
  <section class="words">
    <div class="inner-shadow mustard"></br>
      <h4>FAVORITE MEMORIES</h4></div>
      <div class="container">
        <div class="box_left wisewords">
          <div class="left">
            <%= image_tag "https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAYHAAAAJGE2OWQ0ZDk2LTE1MTctNDc4Mi05ZWUzLTE5ZTExOTUwZTM4OA.jp" %></div>
            <div class="boxHeader-left">
            <h3>Alexa Klein</h3>
          </div>
          <div class="quotemark-open">
            <%= image_tag "quote-front-black" %>
          </div>
          <div class="textContainer">
          <h2> I have loved meeting and learning from such a diverse and awesome group of people. </h2>
        </div>
        <div class="quotemark-close">
          <%= image_tag "quote-end-black" %>
        </div>
      </div>
    </div>
      <div class="container">
        <div class="box_right wisewords">
          <div class="right">

            <%= image_tag "http://i.imgur.com/msYfTL5l.jpg?1" %>
          </div>
          <div class="boxHeader-right">
          <h3>Brendan Magee</h3>
        </div>
        <div class="quotemark-open">
          <%= image_tag "quote-front-black" %>
        </div>
        <div class="textContainer">
          <h2>Bipin's GA happy hour poetry slam performance.</h2>
        </div>
        <div class="quotemark-close">
          <%= image_tag "quote-end-black" %>
        </div>
      </div>
    </div>
      <div class="container">
        <div class="box_left wisewords">
          <div class="left">
            <%= image_tag "http://i.imgur.com/qJ7gZy2l.jpg" %>
          </div>
          <div class="boxHeader-left">
          <h3>Christine Movius</h3>
        </div>
        <div class="quotemark-open">
          <%= image_tag "quote-front-black" %>
        </div>
        <div class="textContainer">
          <h2>The moments when I witness a fellow classmate celebrating after finally getting their code to work after struggling through a really hard problem.</h2>
        </div>
        <div class="quotemark-close">
          <%= image_tag "quote-end-black" %>
        </div>
      </div>
    </div>
      <div class="container">
        <div class="box_right wisewords">
          <div class="right">
            <%= image_tag"https://pbs.twimg.com/profile_images/494612822740197377/4ldXwgN5_400x400.jpeg" %>
          </div>
          <div class="boxHeader-right">
          <h3>Jesse Shawl</h3>
        </div>
        <div class="quotemark-open">
          <%= image_tag "quote-front-black" %>
        </div>
        <div class="textContainer">
          <h2>That squad scrum we had where talked about how to think positively about life.</h2>
        </div>
        <div class="quotemark-close">
          <%= image_tag "quote-end-black" %>
        </div>
      </div>
    </div>
        <div class="container">
          <div class="box_left wisewords">
            <div class="left">
              <%= image_tag"https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAhyAAAAJGZhYjkxOTZkLTA2NGEtNGQ0Ny1hODhhLWE2Zjk0ZWY3OGU2MQ.jpg"%>
            </div>
            <div class="boxHeader-left">
            <h3>Robel Tekeste</h3>
          </div>
          <div class="quotemark-open">
            <%= image_tag "quote-front-black" %>
          </div>
          <div class="textContainer">
            <h2> Juan 'The Wombat' Jaunnsen </h2>
          </div>
          <div class="quotemark-close">
            <%= image_tag "quote-end-black" %>
          </div>
        </div>
      </div>
        <div class="container">
          <div class="box_right wisewords">
            <div class="right">
              <%= image_tag"https://avatars3.githubusercontent.com/u/10698044?v=3&s=460"%>
            </div>
            <div class="boxHeader-right">
            <h3>Nick Olds</h3>
          </div>
          <div class="quotemark-open">
            <%= image_tag "quote-front-black" %>
          </div>
          <div class="textContainer">
            <h2>Celebrating my birthday with the cohort and with cake!</h2>
          </div>
          <div class="quotemark-close">
            <%= image_tag "quote-end-black" %>
          </div>
        </div>
      </div>
          <div class="container">
            <div class="box_left wisewords">
              <div class="left">
                <%= image_tag"http://i.imgur.com/00vZ2AHl.jpg?1"%>
              </div>
              <div class="boxHeader-left">
              <h3>Craig Eisen</h3>
            </div>
            <div class="quotemark-open">
              <%= image_tag "quote-front-black" %>
            </div>
            <div class="textContainer">
              <h2>I do not have a specific memory, but will always remember the enthusiasm shared by the teachers, students, and admins at GA.</h2>
            </div>
            <div class="quotemark-close">
              <%= image_tag "quote-end-black" %>
            </div>
          </div>
        </div>
          <div class="container">
            <div class="box_right wisewords">
              <div class="right">
                <%= image_tag"http://i.imgur.com/zQy0102l.jpg"%>
              </div>
              <div class="boxHeader-right">
              <h3>Vijender Bajwa</h3>
            </div>
            <div class="quotemark-open">
              <%= image_tag "quote-front-black" %>
            </div>
            <div class="textContainer">
              <h2>That one time we went to the pub.</h2>
            </div>
            <div class="quotemark-close">
              <%= image_tag "quote-end-black" %>
            </div>
          </div>
        </div>
        <div class="container">
          <div class="box_left wisewords">
            <div class="left">
              <%= image_tag"http://i.imgur.com/82gCrYUm.jpg"%>
            </div>
            <div class="boxHeader-left">
            <h3>Farishta Haider</h3>
          </div>
          <div class="quotemark-open">
            <%= image_tag "quote-front-black" %>
          </div>
          <div class="textContainer">
            <h2>One of the best memories was the exercise when we all wrote anonymous comments about each other. </h2>
          </div>
          <div class="quotemark-close">
            <%= image_tag "quote-end-black" %>
          </div>
        </div>
      </div>
      </section>
      <section class="space">
      </section>
      <section>
        <section class="bottom">
          <div class="bottom_container">
            <div class="photos">
              <div class="bg">
                <div class="text-overlay">
                  <div class="inner-shadow mustard">
                  </br>
                </br>
                <span3>PHOTO GALLERY</span3>
                <%=link_to image_tag("photogallery.png"), photos_path(@photo)%>
              </div>
            </div>
          </section>
          <section class="space">
          </section>
        </section>
      </br>
      <footer>
        <%= image_tag("blkdc.png") %>
      </footer>