config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'yearbook#index'
  get 'tags/:tag', to: 'photo#index', as: "tag"

  resources :wdiers do
    resources :posts
  end
  resources :wdiers do
    resources :students
  end

  resources :wdiers do
    resources :instructors
  end

  resources :photos
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :negatives
  has_many :instructors, through: :negatives
  has_many :students, through: :negatives
  has_many :users, through: :negatives
  has_many :wdiers, through: :negatives
  belongs_to :yearbook
  # acts_as_taggable
  # acts_as_taggable_on :name

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).photos
  end

  def self.tag_counts
    Tag.select("tags.id, tags.name,count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id, tags.id, tags.name")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

  #
  # validates_attachment :image,
  #                      content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  # has_attached_file :image,
  #                   styles: { thumb: ["64x64#", :jpg] }
  #
  #                   has_attached_file :image,
  #                                     styles: { thumb: ["64x64#", :jpg],
  #                                               original: ['500x500>', :jpg] },
  #                                     convert_options: { thumb: "-quality 75 -strip",
  #                                                        original: "-quality 85 -strip" },
  #                                     storage: :s3,
  #                                     s3_credentials: {access_key_id: ENV["AWS_KEY"], secret_access_key: ENV["AWS_SECRET"]},
  #                                     bucket: "wdi8"
  # s3_region: ENV["aws_region"],
end

# # class Post
#   self.per_page = 25
#
#
# # set per_page globally
# WillPaginate.per_page = 25

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # acts_as_taggable # Alias for acts_as_taggable_on :tags
  # acts_as_taggable_on :name


  def index
    # if params[:tag]
    #   @photos = Photo.tagged_with(params[:tag])
    # else
    @photos = Photo.all
    @photos = Photo.paginate(:page => params[:page])
    end
  # end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.create!(photo_params)
    if @photo.save
      flash[:success] = "The photo was added"

    redirect_to photo_path(@photo)
  else
    render 'new'
  end
end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
     @photo.update!(photo_params)
    else
      redirect_to photo_path(@photo)
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    redirect_to photos_path(@photo)
  end

  # def attr_accessible
  #   @photo = Photo.find(params[:id])
  # end

  private
  def photo_params
    params.require(:photo).permit( :caption, :img_url, :tag_list, :all_tags)
  end
end

app/views/photos/_new.html.erb
<div class="row text-center">
  <%= form_for(Photo.new) do |f| %>
    <div class="large-10 large-centered columns">
      <%= f.text_field :img_url, placeholder: "Enter the photo URL" %>
    </div>
    <div class="large-10 large-centered columns">
      <%= f.text_field :all_tags, placeholder: "Enter your tags, separated with commas" %>
    </div>
    <div class="large-10 large-centered columns">
      <%= f.submit "Post", class: "button"%>
    </div>
  <% end %>
</div>

app/views/photos/edit.html.erb
<style>
#form {
  margin-top: 400px;
  height: 1000px;
}

#form .fill{
  height: 800px;
  width: 600px;
  background: red;
  color: #000;
}
</style>
<section class="form">
<h2>Edit photo</h2>
<%= form_for @photo do |f| %>
<div class="row text-center">
  <div class="large-10 large-centered columns">

<%=f.label :img_url, "Photo URL" %>
<%=f.text_field :img_url %>
</br>
<%=f.label :caption, "Caption" %>
<%=f.text_field :caption%>
</br>
<%=f.label :all_tags,"Tags", placeholder: "Separated with commas" %>
<%= f.text_field :all_tags %>
</br>
<%=f.submit%>
  <% end %>
<div>
</section>
<footer>
  <%= image_tag("blkdc.png") %>
</footer>

app/views/photos/index.html.erb
<section class="photoIndex">


<!-- <div id="tag_cloud">
tag_cloud Photo.tag_counts, %w[s m l] do |tag, css_class|
link_to tag.name, tag_path(tag), css_class
end
  </div> -->
<!-- <#%= raw photo.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(',') %> -->

  <section id="photo">
    <div class="space">
      <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <%= render partial: "photos/new" %>
      </div>
      <div class="inner-shadow mustard" >
        <h2> WDI 8 Photo Gallery </h2></div>
        <button class="button"><%= link_to "New Photo", new_photo_path(@photo)%></button>
        <div class="index">
          <div class="photoGallery">
            <div class='imgGalleryContainer'>
              <div class="thumbnail">
                <ul>
                  <li><% @photos.each do |photo| %>
                    <%= link_to image_tag(photo.img_url), photo_path(photo)%>
                    <%= render @photos %></img>
                    <% end %>
                  </li>
                </ul>
              </div>
            </div>
            <div class="digg_pagination">
              <div class="page_info">
                <%= page_entries_info @photos %>
              </div>
                <%= will_paginate @photos, :container => false %>
            </div>
          </div>
        </div>
      </section>
    </section>

app/views/photos/new.html.erb
<section id="comment_form">
  <%= form_for @photo do |f| %>
  <div class="inner-shadow mustard">
  </br>
  </br>
  </br>
  <h4>PHOTO</h4>
</div>
  <div class="box">
  <div class="insidebox">
    <div class="input">
          <%=f.label :img_url, "Photo URL" %>
          <%=f.text_field :img_url %>
        </div>
        <div class="input">
          <%=f.label :caption, "Caption" %>
          <%=f.text_field :caption%>
        </div>
        <div class="input">
        <%=f.label :all_tags,"Tags", placeholder: "Separated with commas" %>
        <%= f.text_field :all_tags %>
      </div>
      <button><%= f.submit "Post", class: "button"%></button>
      <% end %>
    </div>
    </div>
</section>
<footer>
  <%= image_tag("blkdc.png") %>
</footer>

app/views/photos/show.html.erb
<section id="photoShow">
  <%= image_tag @photo.img_url%></br>
  <%= @photo.caption %></br>
  <%= @photo.tag %></br>
  <%= @photo.tagging %></br>
  <button><%= link_to "Edit", edit_photo_path(@photo) %> </button></br>
  <button><%= link_to "Delete", photo_path(@photo),  method: :delete %> </button></br>
  <button><%= link_to "Back to Gallery", photos_path(@photo) %> </button></br>
    </img>
</section>
<footer>
  <%= image_tag("blkdc.png") %>
</footer>